language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0
  - jruby
before_install:
  - gem install bundler
  - ssh-keygen -q -t rsa -N "" -f ~/.ssh/id_rsa
  - cp $HOME/.ssh/id_rsa.pub $HOME/.ssh/authorized_keys