---
A: ĄΑΔΛ
B: ßɃΒ
C: ĆĈĊČϚ
D: ÐĎĐ
E: ĘƐЗŒΣΞ
F: ƑϜ
G: ĜĞĠĢƓǦ
H: ĤĦ
I: Įİ
J: Ĵ
K: ĶĸƘ
L: ĹĻĽĿŁ
N: ŃŅŇŊИ
O: ØƟƠΘΩ
P: ÞƤΡ
R: ŔŖŘЯƦ
S: ŚŜŞŠƧ
T: ŢŤŦГΓΤ
U: ŲƱ
W: Ŵ
X: Χ
Y: ÝŶЧ
Z: ŹŻŽ
a: ąæαδλ
b: Ƅƀƅβ
c: Ɔćĉċčɔϛ
d: ðďđ
e: Əęɛəзœɘςξ
f: ƒϝ
g: ĝğġģɠǧ
h: ĥħ
i: īį
j: ĵ
k: ķƙ
l: ĺļľŀł
n: ŉńņňŋиȠƞ
o: øɵơθω
p: þƥρ
r: ŕŗřяʀ
s: śŝşšƨ
t: ţťŧгγτ
u: ųʊ
w: ŵ
x: ×χ
y: ÿýŷч
z: źżž